### ISSUE TITLE
Adding context paragraph at the beginning

### ISSUE THREAD

**Issue by astroash** [foundersandcoders/ws-database-testing#17]
It would be great if the workshop started with a paragraph explaining why it's important to have test databases, and what would happen if there wasn't one. It can help grab students attention from the beginning and help them relate it to what they're going to build in projects.

**Comment by azayneeva** [comment]
done! :)

**Comment by astroash** [comment]
I don't think this issue is closed yet. To make this workshop usable across FAC campuses I would put more detail in why test databases are useful.
